// Este archivo contiene todos los productos del menú de La Ventanita Gorroles
// Se importará en seed.ts para poblar la base de datos

export interface ProductoSeed {
  nombre: string;
  descripcion?: string;
  precio: number;
  idcategoria: number;
  activo: boolean;
  disponible: boolean;
  tiempoPreparacion?: number;
  tieneVariantes: boolean;
  precioVariable: boolean;
}

export const productosMenu: ProductoSeed[] = [
  // ========== POLLO FRITO ==========
  {
    nombre: "Porción de Pechuga",
    descripcion: "Porción de pechuga de pollo frito",
    precio: 2500,
    idcategoria: 1,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Porción de Muslo",
    descripcion: "Porción de muslo de pollo frito",
    precio: 2000,
    idcategoria: 1,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Porción Picada",
    descripcion: "Porción de pollo picado frito",
    precio: 3000,
    idcategoria: 1,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Pieza Pechuga",
    descripcion: "Pieza adicional de pechuga",
    precio: 2000,
    idcategoria: 1,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Pieza de Muslo",
    descripcion: "Pieza adicional de muslo",
    precio: 1100,
    idcategoria: 1,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Pieza de Ala",
    descripcion: "Pieza adicional de ala",
    precio: 1000,
    idcategoria: 1,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Pieza Cuarto",
    descripcion: "Pieza adicional de cuarto",
    precio: 1500,
    idcategoria: 1,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: false,
    precioVariable: false,
  },

  // ========== ALITAS ==========
  {
    nombre: "Orden de Alitas",
    descripcion: "Alitas de pollo con diferentes tamaños y salsas",
    precio: 0, // Precio variable según tamaño
    idcategoria: 2,
    activo: true,
    disponible: true,
    tiempoPreparacion: 25,
    tieneVariantes: true,
    precioVariable: true,
  },

  // ========== NUGGETS ==========
  {
    nombre: "Nuggets de pollo",
    descripcion: "Nuggets de pollo con diferentes preparaciones",
    precio: 0, // Precio variable según preparación
    idcategoria: 3,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: true,
    precioVariable: true,
  },

  // ========== COMBOS ==========
  {
    nombre: "Familiar",
    descripcion: "2 Porciones de Pechuga, 2 Porciones de Muslo, 1 Orden de papas o doraditas, 2 bananitos y 2 ensaladas dulce, 1 Refresco 2.5L",
    precio: 13000,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 30,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "8 Piezas",
    descripcion: "Cuarto y Muslo, 1 Refresco 1.5L",
    precio: 7500,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 25,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "La Ventanita",
    descripcion: "4 Porciones de Pechuga, 1 Orden de papas, 4 bananitos o ensalada dulce, 1 Refresco 2.5L",
    precio: 15000,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 30,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Combo #1",
    descripcion: "Combo individual #1",
    precio: 4800,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Combo #2",
    descripcion: "Combo individual #2",
    precio: 4300,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Combo #3",
    descripcion: "Combo individual #3",
    precio: 5000,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Combo #4",
    descripcion: "Combo individual #4",
    precio: 5000,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Para Compartir",
    descripcion: "Combo para compartir",
    precio: 20000,
    idcategoria: 4,
    activo: true,
    disponible: true,
    tiempoPreparacion: 35,
    tieneVariantes: false,
    precioVariable: false,
  },

  // ========== PARA PICAR ==========
  {
    nombre: "Aros de cebolla",
    descripcion: "Aros de cebolla empanizados",
    precio: 2300,
    idcategoria: 5,
    activo: true,
    disponible: true,
    tiempoPreparacion: 10,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Palitos de queso",
    descripcion: "Palitos de queso empanizados",
    precio: 2300,
    idcategoria: 5,
    activo: true,
    disponible: true,
    tiempoPreparacion: 10,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Papas pequeñas",
    descripcion: "Orden de papas fritas pequeñas",
    precio: 2000,
    idcategoria: 5,
    activo: true,
    disponible: true,
    tiempoPreparacion: 8,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Papas grandes",
    descripcion: "Orden de papas fritas grandes",
    precio: 2700,
    idcategoria: 5,
    activo: true,
    disponible: true,
    tiempoPreparacion: 8,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Salchipapas",
    descripcion: "Papas fritas con salchichas",
    precio: 2700,
    idcategoria: 5,
    activo: true,
    disponible: true,
    tiempoPreparacion: 12,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Doraditas",
    descripcion: "Plátano maduro frito",
    precio: 1500,
    idcategoria: 5,
    activo: true,
    disponible: true,
    tiempoPreparacion: 10,
    tieneVariantes: false,
    precioVariable: false,
  },

  // ========== HAMBURGUESAS ARTESANALES ==========
  {
    nombre: "La Clásica",
    descripcion: "Hamburguesa de pollo clásica",
    precio: 4000,
    idcategoria: 6,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "La BBQ",
    descripcion: "Hamburguesa de pollo con pechuga bañada en BBQ",
    precio: 4500,
    idcategoria: 6,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "La Honey",
    descripcion: "Hamburguesa de pollo con pechuga bañada en mostaza miel",
    precio: 4500,
    idcategoria: 6,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "La Hot",
    descripcion: "Hamburguesa de pollo con pechuga bañada en salsa búfalo",
    precio: 4500,
    idcategoria: 6,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Sencilla",
    descripcion: "Hamburguesa de carne sencilla",
    precio: 4000,
    idcategoria: 6,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Doble Torta",
    descripcion: "Hamburguesa de carne con doble queso",
    precio: 6000,
    idcategoria: 6,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Gorroburguesa",
    descripcion: "Torta de carne, pechuga de pollo empanizada y tocino con mozzarella y queso cheddar",
    precio: 6500,
    idcategoria: 6,
    activo: true,
    disponible: true,
    tiempoPreparacion: 22,
    tieneVariantes: true,
    precioVariable: false,
  },

  // ========== SÁNDWICHES ==========
  {
    nombre: "Sándwich de carne",
    descripcion: "Sándwich de carne",
    precio: 2700,
    idcategoria: 7,
    activo: true,
    disponible: true,
    tiempoPreparacion: 12,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Sándwich de pollo a la plancha",
    descripcion: "Sándwich de pollo a la plancha",
    precio: 2700,
    idcategoria: 7,
    activo: true,
    disponible: true,
    tiempoPreparacion: 12,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Sándwich de pollo empanizado",
    descripcion: "Sándwich de pollo empanizado",
    precio: 3000,
    idcategoria: 7,
    activo: true,
    disponible: true,
    tiempoPreparacion: 12,
    tieneVariantes: true,
    precioVariable: false,
  },

  // ========== ESPECIALIDADES DE LA CASA ==========
  {
    nombre: "Nacho de pollo",
    descripcion: "Nachos con pollo",
    precio: 3600,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Nacho de carne",
    descripcion: "Nachos con carne",
    precio: 3600,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Nacho mixto",
    descripcion: "Nachos con pollo y carne",
    precio: 4000,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Papa suprema de pollo",
    descripcion: "Papa rellena con pollo",
    precio: 4000,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Papa suprema de carne",
    descripcion: "Papa rellena con carne",
    precio: 4000,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Papa suprema mixta",
    descripcion: "Papa rellena con pollo y carne",
    precio: 4500,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 18,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Super taco",
    descripcion: "Taco especial",
    precio: 2200,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 12,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Raviol",
    descripcion: "Raviol especial",
    precio: 2200,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 12,
    tieneVariantes: true,
    precioVariable: false,
  },
  {
    nombre: "Torta arreglada",
    descripcion: "Torta arreglada especial",
    precio: 2000,
    idcategoria: 8,
    activo: true,
    disponible: true,
    tiempoPreparacion: 10,
    tieneVariantes: true,
    precioVariable: false,
  },

  // ========== PLATOS FUERTES ==========
  {
    nombre: "Arroz con pollo",
    descripcion: "Arroz con pollo acompañado de papas fritas y ensalada",
    precio: 4500,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 25,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Pechuga a la plancha",
    descripcion: "Pechuga de pollo a la plancha",
    precio: 4500,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Pechuga empanizada",
    descripcion: "Pechuga de pollo empanizada",
    precio: 4800,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Fajitas de pollo a la plancha",
    descripcion: "Fajitas de pollo a la plancha",
    precio: 4500,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 22,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Pollo Naked",
    descripcion: "Pechuga en ensalada",
    precio: 4000,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Ensalada de pollo empanizado",
    descripcion: "Ensalada con pollo empanizado",
    precio: 4200,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Ensalada de pollo a la plancha",
    descripcion: "Ensalada con pollo a la plancha",
    precio: 4000,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 15,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Casado",
    descripcion: "Acompañado de carne del día, arroz, frijoles, ensalada, plátano maduro y fresco natural",
    precio: 3500,
    idcategoria: 9,
    activo: true,
    disponible: true,
    tiempoPreparacion: 20,
    tieneVariantes: false,
    precioVariable: false,
  },

  // ========== REFRESCOS ==========
  {
    nombre: "Gaseosa",
    descripcion: "Gaseosa en diferentes tamaños",
    precio: 0, // Precio variable según tamaño
    idcategoria: 10,
    activo: true,
    disponible: true,
    tiempoPreparacion: 2,
    tieneVariantes: true,
    precioVariable: true,
  },
  {
    nombre: "Café Negro",
    descripcion: "Café negro",
    precio: 800,
    idcategoria: 10,
    activo: true,
    disponible: true,
    tiempoPreparacion: 5,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Café con leche",
    descripcion: "Café con leche",
    precio: 1000,
    idcategoria: 10,
    activo: true,
    disponible: true,
    tiempoPreparacion: 5,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Chocolate",
    descripcion: "Chocolate caliente",
    precio: 1000,
    idcategoria: 10,
    activo: true,
    disponible: true,
    tiempoPreparacion: 5,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Fresco Natural",
    descripcion: "Fresco natural del día",
    precio: 1300,
    idcategoria: 10,
    activo: true,
    disponible: true,
    tiempoPreparacion: 5,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Botella de agua",
    descripcion: "Botella de agua",
    precio: 1000,
    idcategoria: 10,
    activo: true,
    disponible: true,
    tiempoPreparacion: 1,
    tieneVariantes: false,
    precioVariable: false,
  },

  // ========== ADICIONALES ==========
  {
    nombre: "Orden de jalapeños",
    descripcion: "Orden de jalapeños",
    precio: 500,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 3,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Orden de bananitos",
    descripcion: "Orden de bananitos",
    precio: 500,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 5,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Orden de tortillas",
    descripcion: "Orden de tortillas",
    precio: 500,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 3,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Orden de arroz blanco",
    descripcion: "Orden de arroz blanco",
    precio: 800,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 5,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Ensalada dulce",
    descripcion: "Ensalada dulce",
    precio: 500,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 3,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Mayonesa Casera",
    descripcion: "Mayonesa casera",
    precio: 500,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 1,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Mayonesa Casera 325 ml",
    descripcion: "Mayonesa casera en botella de 325ml",
    precio: 3000,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 1,
    tieneVariantes: false,
    precioVariable: false,
  },
  {
    nombre: "Salsas",
    descripcion: "Salsa a elegir (BBQ, Búfalo, Mostaza Miel)",
    precio: 500,
    idcategoria: 11,
    activo: true,
    disponible: true,
    tiempoPreparacion: 1,
    tieneVariantes: false,
    precioVariable: false,
  },
];

